name: CD

on:
  push:
    branches:
      - main
    # paths:
    #   - ./packages/sdk/typescript/subgraph
  pull_request:
    branches:
      - main
    # paths:
    #   - ./packages/sdk/typescript/subgraph
  workflow_dispatch:

jobs:
  subgraph:
    name: Deploy Subgraph
    runs-on: ubuntu-latest
    strategy:
      matrix:
        network:
          - matic
          - goerli
          - moonbeam
          - bsc
          - chapel
          - mumbai
      fail-fast: true
      max-parallel: 1
    steps:
      - uses: actions/checkout@v3
      - run: yarn --ignore-scripts
        name: Install dependencies
      - run: yarn global add @graphprotocol/graph-cli
        name: Install Graph CLI
      - run: graph auth --product hosted-service ${API_KEY}
        name: Authenticate Graph CLI
        env:
          API_KEY: ${{ secrets.HP_GRAPH_API_KEY }}
      - run: yarn generate
        name: Generate Subgraph
        working-directory: ./packages/sdk/typescript/subgraph
        env:
          NETWORK: ${{ matrix.network }}
      - run: graph deploy --product hosted-service humanprotocol/${NETWORK}
        name: Deploy subgraph
        working-directory: ./packages/sdk/typescript/subgraph
        env:
          NETWORK: ${{ matrix.network }}
