name: CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  core-publish:
    name: Core NPM Publish
    runs-on: ubuntu-latest
    needs: core-test
    steps:
      - uses: actions/checkout@v3
      - run: yarn --ignore-scripts
        name: Install dependencies
      - run: yarn compile
        name: Compile smart contracts
        working_directory: ./packages/core
      - run: yarn publish --access public
        name: Publish NPM package
        working_directory: ./packages/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  subgraph:
    name: Deploy Subgraph
    runs-on: ubuntu-latest
    needs:
      - core-publish
      - subgraph-test
    strategy:
      matrix:
        network:
          - matic
          - goerli
          - moonbeam
          - bsc
          - chapel
          - mumbai
    steps:
      - uses: actions/checkout@v3
      - run: yarn --ignore-scripts
        name: Install dependencies
      - run: graph auth --product hosted-service ${API_KEY}
        name: Authenticate Graph CLI
        env:
          API_KEY: ${{ secrets.HP_GRAPH_API_KEY }}
      - run: yarn generate
        name: Generate Subgraph
        working_direcory: ./packages/sdk/typescript/subgraph
        env:
          NETWORK: ${{ matrix.network }}
      - run: graph deploy --product hosted-service humanprotocol/${NETWORK}
        name: Deploy subgraph
        working_direcory: ./packages/sdk/typescript/subgraph
        env:
          NETWORK: ${{ matrix.network }}
