name: Lint check

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn
        name: Install dependencies
      - run: yarn lint
        name: Run lint
