name: CI

on:
  pull_request:
    paths:
      - ./packages/sdk/typescript/subgraph
  workflow_dispatch:

jobs:
  subgraph-test:
    name: Subgraph Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn --ignore-scripts
        name: Install dependencies
      - run: yarn subgraph:test
        name: Run subgraph test
  subgraph-lint:
    name: Subgraph Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn --ignore-scripts
        name: Install dependencies
      - run: yarn subgraph:lint
        name: Run lint
