name: Python SDK check

on:
  pull_request:
  workflow_dispatch:

jobs:
  python-test:
    name: Python Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn --ignore-scripts
        name: Install node dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        working-directory: ./packages/sdk/python
        run: |
          python -m pip install --upgrade pip
      - name: Python test
        working-directory: ./packages/sdk/python
        run: |
          make run-test
