name: Fortune check

on:
  pull_request:
  workflow_dispatch:

jobs:
  fortune-test:
    name: Fortune Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn --ignore-scripts
        name: Install dependencies
      - run: yarn fortune:test
        name: Run fortune test
