name: Subgraph check

on:
  pull_request:
  workflow_dispatch:

jobs:
  subgraph-test:
    name: Subgraph Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn --ignore-scripts
        name: Install dependencies
      - run: yarn subgraph:test
        name: Run subgraph test
