name: Python SDK check

on:
  pull_request:
  workflow_dispatch:

jobs:
  python-test:
    name: Python Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        run: yarn --ignore-scripts
      - name: Install Python
        uses: VaultVulp/action-pipenv@v2.0.1
        working-directory: ./packages/sdk/python
        with:
          command: install -d
      - name: Python test
        working-directory: ./packages/sdk/python
        run: |
          make run-test
