name: CI

on: [pull_request]

jobs:
  core-test:
    name: Core Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn --ignore-scripts
        name: Install dependencies
      - run: yarn core:test
        name: Run protocol test
  subgraph-test:
    name: Subgraph Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn --ignore-scripts
        name: Install dependencies
      - run: yarn subgraph:test
        name: Run subgraph test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn --ignore-scripts
        name: Install dependencies
      - run: yarn lint
        name: Run lint
