name: Protocol Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/protocol
    steps:
      - uses: actions/checkout@v3
      - uses: borales/actions-yarn@v3.0.0
        with:
          node-version: 16
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test
